# Copia locale per test isolati
LIGHT_THEME = {
    "BACKGROUND": "#f0f8ff",
    "TEXT": "#2c3e50",
    "SECONDARY_TEXT": "#7f8c8d",
    "ACCENT": "#3498db",
    "CARD_BACKGROUND": "#ffffff",
    "SIDEBAR": "#ffffff",
    "INFO_GRADIENT": {"start": "#87ceeb", "end": "#e6f3ff"},
    "HOURLY": "#ffffff",
    "WEEKLY": "#ffffff",
    "CHART": "#ffffff",
    "AIR_POLLUTION": "#ffffff",
    "AIR_POLLUTION_CHART": "#ffffff",
    "BORDER": "#e1e8ed",
    "ICON": "#2c3e50",
    "BUTTON_TEXT": "#ffffff",
    "BUTTON_BACKGROUND": "#3498db",
    "DIALOG_BACKGROUND": "#ffffff",
    "DIALOG_TEXT": "#2c3e50",
    "TEMPERATURE_MAIN": "#2c3e50",
    "WEATHER_DESCRIPTION": "#7f8c8d",
    "CARD_SHADOW": "#00000010",
}
DARK_THEME = {
    "BACKGROUND": "#0d1117",
    "TEXT": "#ff0000",
    "SECONDARY_TEXT": "#0077ff",
    "ACCENT": "#58a6ff",
    "CARD_BACKGROUND": "#161b22",
    "SIDEBAR": "#161b22",
    "INFO_GRADIENT": {"start": "#1f2937", "end": "#0d1117"},
    "HOURLY": "#161b22",
    "WEEKLY": "#161b22",
    "CHART": "#161b22",
    "AIR_POLLUTION": "#161b22",
    "AIR_POLLUTION_CHART": "#161b22",
    "BORDER": "#30363d",
    "ICON": "#f0f6fc",
    "BUTTON_TEXT": "#ffffff",
    "BUTTON_BACKGROUND": "#58a6ff",
    "DIALOG_BACKGROUND": "#161b22",
    "DIALOG_TEXT": "#f0f6fc",
    "TEMPERATURE_MAIN": "#f0f6fc",
    "WEATHER_DESCRIPTION": "#8b949e",
    "CARD_SHADOW": "#00000030",
}
